micronaut:
  server:
    port: ${SERVER_PORT:8081}
  application:
    name: my-employee-data-flyway
  scan:
    packages:
      - com.venkat.config
      - com.venkat.tasks



# Datasource configuration
datasources:
  default:
    url: jdbc:mysql://localhost:3306/emp_flyway_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 5000
    connection-test-query: SELECT 1
    pool-name: MyAppHikariPool
    schema-generate: NONE
    dialect: MYSQL

# JPA/Hibernate configuration
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

# Flyway configuration
flyway:
  datasources:
    default:
      enabled: true

# ShedLock configuration
shedlock:
  enabled: true
  defaults:
    lock-at-most-for: PT1M
  micronaut:
    auto-configure: false # Disable shedlock-micronaut auto-configuration

logging:
  level:
    net.javacrumbs.shedlock: TRACE
#    com.zaxxer.hikari: TRACE
#    org.flywaydb: TRACE
#    org.hibernate.SQL: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE